### ISSUE TITLE
Add columns for # pre & # post when showing results of simple connections

### ISSUE THREAD

**Issue by takemuras** [janelia-flyem/ConnectomeAnalyzer#27]
It will be useful to view total synapse numbers of each neuron result without breaking it down.

**Comment by stephenplaza** [comment]
After discussion, we should create a neuron finder plugin that presumably will re-use the neurons in roi plugin but add the ability to restrict to a given name.

**Comment by stephenplaza** [comment]
I modified a pre-existing plugin to be a neuron finder.  It adds a neuron filter in addition to ROI selection.  There are columns for #voxels, #pre, #post but the data is currently not loaded into the sample database.
